services:
  radiusdesk:
    build:
      context: ./
      dockerfile: Dockerfile-build-radiusdesk
      args:
        radiusdesk_volume: ${RADIUSDESK_VOLUME}
    container_name: radiusdesk
    environment:
      - "DATABASE_HOST=rdmariadb"
      - "DATABASE_HOST_CAKE3=rdmariadb"
      - "DEBUG=true"
    restart: always
    depends_on:
      - "rdmariadb"
    ports:
      - "80:80"
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      # 1. Montages de vos dossiers de code locaux pour le développement
      - ../AmpConf:/var/www/rdcore/AmpConf
      - ../cake4:/var/www/rdcore/cake4
      - ../login:/var/www/rdcore/login
      - ../rd:/var/www/rdcore/rd

      # 2. Volume Anonyme pour masquer le dossier critique 'vendor'
      #    Ceci permet au conteneur d'utiliser ses propres dépendances compilées
      #    lors du build (celles de l'image Docker).
      - /var/www/rdcore/cake4/rd_cake/vendor

  rdmariadb:
    container_name: radiusdesk-mariadb
    image: docker.io/bitnami/mariadb:latest
    restart: always
    environment:
      - "ALLOW_EMPTY_PASSWORD=yes"
      - "MARIADB_USER=rd"
      - "MARIADB_DATABASE=rd"
      - "MARIADB_PASSWORD=rd" # Correction de la faute de frappe "MARDIADB"
    volumes:
      - ${RADIUSDESK_VOLUME}/db_conf/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - rd_data:/bitnami/mariadb
      - ${RADIUSDESK_VOLUME}/db_startup:/tmp

volumes:
  rd_data:

networks:
  default:
    external:
      name: "${RADIUSDESK_NETWORK}"
